### ISSUE TITLE
Fix Remote Image Example Tests

### ISSUE THREAD

**Issue by DomAyre** [microsoft/confidential-aci-examples#132]
Generated security policy appears to only cover 2 of the 5 container groups in the provided ARM template, I suspect this is an issue with the tooling itself but needs investigating and fixing/reporting

**Comment by SethHollandsworth** [comment]
Hey Dom, I took a look and think the issue is similar to one our team found last week. I put in a PR to patch it that will hopefully be merged during the next release cycle starting next week.

Link to related code/PR:
[https://github.com/Azure/azure-cli-extensions/pull/7414/files#diff-03ffce22285e59edb301ce41776a561d64db3551a08a00ea7c073e6011a518cdR415](https://github.com/Azure/azure-cli-extensions/pull/7414/files#diff-03ffce22285e59edb301ce41776a561d64db3551a08a00ea7c073e6011a518cdR415)
